// Spanish labels for everything industries.ts shows people. Stored values
// (industry names, incident types, sub-types) stay in English -- they are data
// shared with the AI and the database -- and are only translated on screen.

export const INDUSTRY_NAME_ES: Record<string, string> = {
  Airline: "Aerolínea",
  Rail: "Ferrocarril",
  "Bus/Coach": "Autobús/Autocar",
  "Maritime/Ferry": "Marítimo/Ferry",
  "Ride-hailing": "Transporte con conductor",
  "Public Transit": "Transporte público",
  "Freight/Logistics": "Carga/Logística",
  Healthcare: "Salud",
  "Financial Services": "Servicios financieros",
  Insurance: "Seguros",
  "Hospitality & Travel": "Hostelería y viajes",
  "Retail & E-commerce": "Comercio y e-commerce",
  "Food & Beverage": "Alimentación y bebidas",
  "Energy & Utilities": "Energía y suministros",
  Telecommunications: "Telecomunicaciones",
  Technology: "Tecnología",
  Education: "Educación",
  "Government & Public Sector": "Gobierno y sector público",
  Manufacturing: "Industria manufacturera",
  Other: "Otro",
  // Values from earlier versions of the dropdown.
  Aviation: "Aviación",
  Transportation: "Transporte",
  Hospitality: "Hostelería",
  Retail: "Comercio",
  "Banking & Finance": "Banca y finanzas",
  Energy: "Energía",
  Government: "Gobierno",
};

export const GROUP_ES: Record<string, string> = {
  Transportation: "Transporte",
  Health: "Salud",
  Finance: "Finanzas",
  Consumer: "Consumo",
  Infrastructure: "Infraestructura",
  Other: "Otros sectores",
};

export const TYPE_LABEL_ES: Record<string, string> = {
  // Defaults
  Safety: "Seguridad",
  Delay: "Retraso",
  "Customer treatment": "Trato al cliente",
  Outage: "Caída del servicio",
  Misinformation: "Desinformación",
  // Industry-specific relabels
  "Delivery delay": "Retraso en la entrega",
  "Care delay": "Retraso en la atención",
  "Patient treatment": "Trato al paciente",
  "Security & fraud": "Seguridad y fraude",
  "Service delay": "Retraso del servicio",
  "Claims delay": "Retraso en siniestros",
  "Fulfilment delay": "Retraso en pedidos",
  "Product & safety": "Producto y seguridad",
  "Food safety": "Seguridad alimentaria",
  "Supply outage": "Corte de suministro",
  "Network outage": "Caída de la red",
  "Product & site safety": "Seguridad de producto y planta",
};

/** Field labels, shared across industries, so keyed by the English text. */
export const FIELD_LABEL_ES: Record<string, string> = {
  Operator: "Operador",
  "Service ID": "ID del servicio",
  "Location code": "Código de ubicación",
  "People impacted": "Personas afectadas",
  Carrier: "Transportista",
  "Shipment/tracking number": "Número de envío/seguimiento",
  "Depot/hub code": "Código de depósito/centro",
  "Shipments/customers impacted": "Envíos/clientes afectados",
  Provider: "Proveedor de salud",
  "Case/encounter ID": "ID de caso/atención",
  "Facility/unit": "Centro/unidad",
  "Patients affected": "Pacientes afectados",
  Institution: "Institución",
  "Transaction/account ref": "Ref. de transacción/cuenta",
  "Branch/region code": "Código de sucursal/región",
  "Customers affected": "Clientes afectados",
  Insurer: "Aseguradora",
  "Policy/claim number": "Número de póliza/siniestro",
  "Region code": "Código de región",
  "Policyholders affected": "Asegurados afectados",
  "Booking reference": "Referencia de reserva",
  "Property/site code": "Código de establecimiento",
  "Guests affected": "Huéspedes afectados",
  Retailer: "Comercio",
  "Order number": "Número de pedido",
  "Store/warehouse code": "Código de tienda/almacén",
  "Batch/order number": "Número de lote/pedido",
  "Site/venue code": "Código de local",
  Utility: "Empresa de suministro",
  "Incident/work order ref": "Ref. de incidencia/orden de trabajo",
  "Grid/zone code": "Código de red/zona",
  "Incident/ticket ref": "Ref. de incidencia/ticket",
  "Cell/region code": "Código de celda/región",
  "Subscribers affected": "Abonados afectados",
  Company: "Empresa",
  "Incident ID": "ID de incidente",
  "Region/cluster": "Región/clúster",
  "Users affected": "Usuarios afectados",
  "Case/reference number": "Número de caso/referencia",
  "Campus/site code": "Código de campus/sede",
  "Students affected": "Estudiantes afectados",
  Agency: "Organismo",
  "Office/region code": "Código de oficina/región",
  "Citizens affected": "Ciudadanos afectados",
  Manufacturer: "Fabricante",
  "Batch/lot number": "Número de lote",
  "Plant/line code": "Código de planta/línea",
  Airline: "Aerolínea",
  "Flight number": "Número de vuelo",
  "Airport code": "Código de aeropuerto",
  "Passengers impacted": "Pasajeros afectados",
  "Rail operator": "Operador ferroviario",
  "Train number": "Número de tren",
  "Station code": "Código de estación",
  "Bus company": "Empresa de autobuses",
  "Route number": "Número de ruta",
  "Stop/terminal code": "Código de parada/terminal",
  "Shipping line": "Naviera",
  "Voyage number": "Número de travesía",
  "Port code": "Código de puerto",
  "Ride-hailing company": "Empresa de transporte con conductor",
  "Trip ID": "ID del viaje",
  "Zone/city code": "Código de zona/ciudad",
  "Riders impacted": "Usuarios afectados",
  "Transit operator": "Operador de transporte",
  "Line/route number": "Número de línea/ruta",
  "Station/stop code": "Código de estación/parada",
};

// Words inside the example placeholders ("e.g. Madrid-Barcelona").
const EXAMPLE_WORDS_ES: Array<[RegExp, string]> = [
  [/\bOrigin\b/g, "Origen"], [/\bDestination\b/g, "Destino"], [/\bWarehouse\b/g, "Almacén"],
  [/\bEmergency\b/g, "Urgencias"], [/\bICU\b/g, "UCI"], [/\bRetail\b/g, "Particulares"],
  [/\bCorporate\b/g, "Empresas"], [/\bHome\b/g, "Hogar"], [/\bStore\b/g, "Tienda"],
  [/\bProduction\b/g, "Producción"], [/\bSubstation\b/g, "Subestación"], [/\bCore\b/g, "Núcleo"],
  [/\bEdge\b/g, "Borde"], [/\bRegion North\b/g, "Región Norte"], [/\bPlant\b/g, "Planta"],
  [/\bDistribution\b/g, "Distribución"], [/\bDowntown\b/g, "Centro"], [/\bAirport\b/g, "Aeropuerto"],
  [/\bNorth-South Line\b/g, "Línea Norte-Sur"], [/\bLine (\d+)/g, "Línea $1"],
];

export function exampleEs(s: string): string {
  let out = s.replace(/^e\.g\. /, "p. ej. ");
  for (const [re, to] of EXAMPLE_WORDS_ES) out = out.replace(re, to);
  return out;
}

export const SUBTYPE_ES: Record<string, string> = {
  abuse_on_platform: "Abuso en la plataforma",
  accessibility_issue: "Problema de accesibilidad",
  account_closure_dispute: "Disputa por cierre de cuenta",
  account_suspension_dispute: "Disputa por suspensión de cuenta",
  admissions_backlog: "Retraso en admisiones",
  allergen_mislabeling: "Error de etiquetado de alérgenos",
  ambulance_diversion: "Desvío de ambulancias",
  api_failure: "Fallo de la API",
  app_or_website_down: "App o web caída",
  application_backlog: "Retraso en solicitudes",
  appointment_backlog: "Retraso en citas",
  assessment_delay: "Retraso en peritaciones",
  atm_network_down: "Red de cajeros caída",
  baggage_system_failure: "Fallo del sistema de equipajes",
  benefits_delay: "Retraso en prestaciones",
  billing_dispute: "Disputa de facturación",
  boarding_system_issue: "Problema del sistema de embarque",
  booking_dispute: "Disputa de reserva",
  booking_system_outage: "Caída del sistema de reservas",
  branch_closure: "Cierre de sucursal",
  broadband_outage: "Caída de banda ancha",
  campus_security_incident: "Incidente de seguridad en el campus",
  cancellation_wave: "Ola de cancelaciones",
  capacity_overflow: "Desbordamiento de capacidad",
  capacity_shortfall: "Falta de capacidad",
  check_in_delay: "Retraso en el check-in",
  checkin_failure: "Fallo del check-in",
  checkout_outage: "Caída del proceso de pago",
  claim_denial_dispute: "Disputa por siniestro rechazado",
  claims_backlog: "Retraso en siniestros",
  claims_portal_down: "Portal de siniestros caído",
  class_cancellation: "Cancelación de clases",
  closure: "Cierre",
  closure_or_refurbishment: "Cierre o reforma",
  connection_backlog: "Retraso en conexiones",
  consent_dispute: "Disputa de consentimiento",
  contamination: "Contaminación",
  contract_dispute: "Disputa contractual",
  core_banking_outage: "Caída del núcleo bancario",
  counterfeit_claims: "Denuncias de falsificación",
  customs_hold: "Retención en aduanas",
  data_breach: "Filtración de datos",
  data_loss: "Pérdida de datos",
  degraded_performance: "Rendimiento degradado",
  delivery_delay: "Retraso en la entrega",
  derailment: "Descarrilamiento",
  disconnection_dispute: "Disputa por corte de suministro",
  discrimination_claim: "Denuncia de discriminación",
  dispatch_failure: "Fallo de asignación",
  driver_conduct: "Conducta del conductor",
  driver_shortage: "Falta de conductores",
  ehr_outage: "Caída de la historia clínica electrónica",
  elective_postponement: "Aplazamiento de cirugías programadas",
  eligibility_dispute: "Disputa de elegibilidad",
  emergency_calls_affected: "Llamadas de emergencia afectadas",
  emergency_stop: "Parada de emergencia",
  environmental_spill: "Vertido ambiental",
  equipment_failure: "Fallo de equipos",
  erp_system_failure: "Fallo del ERP",
  exam_system_failure: "Fallo del sistema de exámenes",
  facility_hazard: "Riesgo en las instalaciones",
  fake_news: "Noticias falsas",
  fake_reviews: "Reseñas falsas",
  false_rumor: "Rumor falso",
  fees_dispute: "Disputa de tasas",
  fire_or_evacuation: "Incendio o evacuación",
  fire_or_explosion: "Incendio o explosión",
  foodborne_illness: "Intoxicación alimentaria",
  fraud_incident: "Incidente de fraude",
  fulfilment_delay: "Retraso en pedidos",
  gas_leak: "Fuga de gas",
  gas_supply_failure: "Fallo del suministro de gas",
  grading_dispute: "Disputa de calificaciones",
  grounding_or_collision: "Encallamiento o colisión",
  hazmat_incident: "Incidente con mercancías peligrosas",
  health_misinformation: "Desinformación sanitaria",
  hub_disruption: "Interrupción en el centro de operaciones",
  imaging_system_failure: "Fallo del sistema de imagen",
  infection_outbreak: "Brote infeccioso",
  ingredient_rumor: "Rumor sobre ingredientes",
  injury_report: "Aviso de lesión",
  insider_misconduct: "Conducta indebida interna",
  installation_backlog: "Retraso en instalaciones",
  inventory_system_failure: "Fallo del sistema de inventario",
  key_system_failure: "Fallo del sistema de llaves",
  lab_system_failure: "Fallo del sistema de laboratorio",
  learning_platform_outage: "Caída de la plataforma educativa",
  level_crossing_incident: "Incidente en paso a nivel",
  lost_or_damaged_goods: "Mercancía perdida o dañada",
  man_overboard: "Hombre al agua",
  manipulated_content: "Contenido manipulado",
  market_rumor: "Rumor de mercado",
  mast_or_site_incident: "Incidente en antena o emplazamiento",
  medical_emergency: "Emergencia médica",
  medication_error: "Error de medicación",
  metering_system_down: "Sistema de medición caído",
  mis_selling_claim: "Denuncia de venta indebida",
  misleading_video: "Vídeo engañoso",
  missed_connections: "Conexiones perdidas",
  mobile_service_down: "Servicio móvil caído",
  network_outage: "Caída de la red",
  onboard_incident: "Incidente a bordo",
  ordering_system_down: "Sistema de pedidos caído",
  overbooking: "Sobreventa",
  passenger_assault: "Agresión a pasajero",
  passenger_removal: "Expulsión de pasajero",
  patient_harm: "Daño al paciente",
  payment_delay: "Retraso en pagos",
  payment_system_failure: "Fallo del sistema de pago",
  payments_outage: "Caída de pagos",
  payout_delay: "Retraso en indemnizaciones",
  permit_delay: "Retraso en permisos",
  physical_security_event: "Incidente de seguridad física",
  planned_works_overrun: "Obras programadas prolongadas",
  plant_system_outage: "Caída de sistemas de planta",
  policy_misinformation: "Desinformación sobre políticas",
  policy_system_outage: "Caída del sistema de pólizas",
  portal_outage: "Caída del portal",
  pos_outage: "Caída del punto de venta",
  power_outage: "Corte eléctrico",
  privacy_complaint: "Queja de privacidad",
  processing_backlog: "Retraso en tramitación",
  product_recall: "Retirada de producto",
  product_safety_defect: "Defecto de seguridad del producto",
  production_halt: "Parada de producción",
  provisioning_delay: "Retraso en altas de servicio",
  public_safety_incident: "Incidente de seguridad pública",
  records_system_failure: "Fallo del sistema de registros",
  refund_dispute: "Disputa de reembolso",
  regulatory_breach: "Incumplimiento normativo",
  release_rollback: "Reversión de versión",
  restoration_delay: "Retraso en el restablecimiento",
  results_delay: "Retraso en resultados",
  road_collision: "Colisión en carretera",
  safeguarding_incident: "Incidente de protección",
  safety_event: "Incidente de seguridad",
  sanctions_breach: "Incumplimiento de sanciones",
  scheduling_system_down: "Sistema de citas caído",
  security_incident: "Incidente de seguridad",
  security_vulnerability: "Vulnerabilidad de seguridad",
  service_complaint: "Queja sobre el servicio",
  service_delay: "Retraso del servicio",
  service_outage: "Caída del servicio",
  settlement_failure: "Fallo de liquidación",
  shipment_delay: "Retraso en envíos",
  signalling_failure: "Fallo de señalización",
  social_media_backlash: "Reacción en redes sociales",
  sorting_system_failure: "Fallo del sistema de clasificación",
  staff_behavior_issue: "Problema de conducta del personal",
  staff_misconduct: "Conducta indebida del personal",
  staff_shortage: "Falta de personal",
  stockout: "Rotura de stock",
  store_security_incident: "Incidente de seguridad en tienda",
  student_harm: "Daño a estudiante",
  supply_shortage: "Escasez de suministro",
  support_backlog: "Retraso en soporte",
  surge_disruption: "Interrupción por alta demanda",
  surgical_complication: "Complicación quirúrgica",
  system_outage: "Caída del sistema",
  technical_failure: "Fallo técnico",
  ticketing_failure: "Fallo de venta de billetes",
  tracking_system_failure: "Fallo del sistema de seguimiento",
  trading_platform_down: "Plataforma de negociación caída",
  vehicle_failure: "Avería del vehículo",
  warehouse_accident: "Accidente en almacén",
  warranty_dispute: "Disputa de garantía",
  water_supply_failure: "Fallo del suministro de agua",
  workplace_injury: "Accidente laboral",
  zone_outage: "Caída en la zona",
};
