-- This migration originally wiped ALL incidents (DELETE FROM public.incidents,
-- unlinking incident_assets/social_mentions) and seeded 10 Aurora Skylines
-- demo incidents unconditionally. That meant any brand-new client's fresh
-- Supabase project would get fake airline data wiped into their real
-- incidents table on first `supabase db push` (Sevra is one deployment per
-- client, so a fresh project should start with an empty incidents table).
--
-- The destructive seed block has been removed. This is safe for
-- already-migrated projects (this one included) — Supabase tracks applied
-- migration *version numbers*, not file content checksums, so editing this
-- historical file does not re-run anything here. It only changes what a
-- brand-new client's fresh migration history will do.
--
-- Airline-flavored demo data (if wanted for a demo/sales environment) lives
-- in supabase/seed.sql instead, which is opt-in (`supabase db seed`) and
-- never runs automatically.
